name: Auto Post

on:
  workflow_dispatch: # 수동 실행
  schedule:
    - cron: '0 0 * * *' # 매일 실행 시간 설정

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install openai google-auth-oauthlib google-api-python-client requests

      - name: Run post script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_TOKEN_JSON: ${{ secrets.GOOGLE_TOKEN_JSON }}
          CLENT_SECRET: ${{ secrets.CLENT_SECRET }}
        run: |
          python main.py
