name: Auto Post

on:
  workflow_dispatch:  # 이걸 두면 수동 실행도 여전히 가능합니다.
  schedule:
    - cron: '0 0 * * *'  # 이 시간은 UTC 기준입니다. 한국 시간(KST) 아침 9시를 맞추려면 이 값을 설정해야 합니다.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Make client_secret.json from GitHub Secret
        run: echo '${{ secrets.CLENT_SECRET }}' > client_secret.json

      - name: Run script
        run: python main.py
